# Generated by Django 5.2.4 on 2025-07-22 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_role', models.CharField(max_length=10)),
                ('new_role', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_changes_made', to=settings.AUTH_USER_MODEL)),
                ('changed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_changes_recieved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
