# Generated by Django 5.2.3 on 2025-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rolechangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolechangelog',
            name='new_role',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rolechangelog',
            name='old_role',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('internal_admin', 'Internal Admin')], default='user', max_length=15),
        ),
    ]
