# Generated by Django 5.2.3 on 2025-11-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_image_to_url'),
        ('accounts', '0007_user_image'),
    ]

    operations = [
    ]
