# Generated by Django 5.2.3 on 2025-08-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
    ]
