# Generated by Django 5.2.3 on 2026-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20250811_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
