# Generated by Django 5.2.4 on 2025-08-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='trailer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
