# Generated by Django 5.2.3 on 2025-08-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('music', 'Music'), ('series', 'Series'), ('original', 'Original'), ('documentary', 'Documentary')], max_length=20),
        ),
    ]
