# Generated by Django 5.2.3 on 2025-08-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='season',
            name='trailer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
