# Generated by Django 5.2.3 on 2025-09-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_season_description_season_trailer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='writer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('music', 'Music'), ('series', 'Series'), ('original', 'Original'), ('documentary', 'Documentary'), ('animations', 'Animations')], max_length=20),
        ),
    ]
