# Generated by Django 5.2.3 on 2025-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_director_content_genre_content_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
