# Generated by Django 5.2.3 on 2025-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_episode_thumbnail_season_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='contentadverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_type', models.CharField(choices=[('hello', 'Hello'), ('stream', 'Stream'), ('middle', 'Middle')], max_length=20)),
                ('advert_name', models.CharField(blank=True, max_length=200, null=True)),
                ('advert_description', models.TextField(blank=True, null=True)),
                ('advert_link', models.URLField(blank=True, null=True)),
                ('stream_link', models.URLField(blank=True, null=True)),
                ('advert_thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
