# Generated by Django 5.2.3 on 2025-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentadverts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentadverts',
            name='advert_type',
            field=models.CharField(choices=[('hello', 'Hello'), ('stream', 'Stream'), ('middle', 'Middle'), ('end', 'End')], max_length=20),
        ),
    ]
