# Generated by Django 5.2.3 on 2025-09-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_contentadverts_advert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
