# Generated by Django 5.2.3 on 2025-09-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_country_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(blank=True, choices=[('preview', 'Preview'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('comingsoon ', 'Comingsoon')], max_length=100, null=True),
        ),
    ]
