# Generated by Django 5.2.3 on 2025-10-08 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('music', 'Music'), ('series', 'Series'), ('miniseries', 'Miniseries'), ('original', 'Original'), ('documentary', 'Documentary'), ('animations', 'Animations')], max_length=20),
        ),
        migrations.CreateModel(
            name='MiniSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('miniseries_no', models.PositiveIntegerField()),
                ('streaming_link', models.URLField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniseries', to='content.content')),
            ],
        ),
    ]
