# Generated by Django 5.2.3 on 2026-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_normalize_content_comingsoon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
