"""
Django settings for cbmtv project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ("1", "true", "yes", "on")


def env_list(name, default=None):
    value = os.environ.get(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


STATIC_ROOT = BASE_DIR / "staticfiles"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-l-lxx-*u2my&r*8p66%m*ppf+shl8s_@cz3(njf7xabcj2dg)(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)

# Django's DEFAULT_LOGGING gates its console handler behind require_debug_true
# and routes `django.request` ERRORs (i.e. every unhandled 500) to mail_admins.
# With DEBUG=False and no ADMINS/email backend — which is exactly how this
# deploys — that means 500 tracebacks are discarded and the platform log shows
# only the gunicorn access line. Log them to stdout instead so `railway logs`
# (or `docker compose logs`) shows why a request failed.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.db.backends": {
            # Flip to DEBUG via DJANGO_DB_LOG_LEVEL to see the failing SQL.
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_DB_LOG_LEVEL", "WARNING"),
            "propagate": False,
        },
    },
}

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", [
    "127.0.0.1",
    "localhost",
    "api.cbmtv.online",
    "backend.cbmtv.online",
    "apicbmtv.cbmgroupco.com",
    ".onrender.com",
])

# The live frontends are cbmtv.cbmgroupco.com (stream) and
# cbmtv-dashboard-five.vercel.app (dashboard). cbmtv-dashboard.vercel.app is a
# stale Vercel deployment that no longer tracks main -- deliberately not trusted
# here, so it cannot act against this API.
#
# The cbmtv.online names below do not currently resolve. They are kept because
# the domain is ours and may be pointed here later; they grant nothing while
# DNS is absent.
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", [
    "http://localhost:8080",
    "http://localhost:8000",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:5137",
    "http://cbmtv.online",
    "https://cbmtv.online",
    "https://www.cbmtv.online",
    "https://cbmtv.cbmgroupco.com",
    "https://apicbmtv.cbmgroupco.com",
    "https://cbmtv-ui.vercel.app",
    "https://cbmtv-dashboard-five.vercel.app",
    "https://api.cbmtv.online",
    "https://backend.cbmtv.online",
    "https://*.onrender.com",
])

# Production overrides this via the CORS_ALLOWED_ORIGINS env var, which already
# lists the two live frontends. This default exists for local and any deploy that
# does not set it, and is kept in step with the CSRF list above.
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", [
    "http://localhost:8080",
    "http://localhost:8000",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:5137",
    "http://cbmtv.online",
    "https://cbmtv.online",
    "https://www.cbmtv.online",
    "https://cbmtv.cbmgroupco.com",
    "https://cbmtv-ui.vercel.app",
    "https://cbmtv-dashboard-five.vercel.app",
])

# Origins a developer's browser actually uses: the stream app, the dashboard,
# and Expo's web/Metro ports for the mobile app. Native mobile builds do not
# send an Origin header and are unaffected by CORS either way.
LOCAL_DEV_CORS_ORIGINS = [
    "http://localhost:3000", "http://127.0.0.1:3000",
    "http://localhost:3001", "http://127.0.0.1:3001",
    "http://localhost:3100", "http://127.0.0.1:3100",
    "http://localhost:8081", "http://127.0.0.1:8081",
    "http://localhost:19006", "http://127.0.0.1:19006",
]

# The deployed backend sets CORS_ALLOWED_ORIGINS, and that env var REPLACES the
# default list above -- which is why the live API rejects every localhost
# origin, and why the stream app cannot be run locally against it.
#
# Rather than loosening the production allowlist, local origins are appended
# only when this instance is explicitly a development one: either DEBUG is on,
# or CORS_ALLOW_LOCAL_DEV is set. Production runs DEBUG=false and does not set
# that flag, so its allowlist is byte-for-byte unchanged. A staging deploy that
# wants to serve local frontends can opt in with CORS_ALLOW_LOCAL_DEV=true
# without anyone reaching for CORS_ALLOW_ALL_ORIGINS.
if DEBUG or env_bool("CORS_ALLOW_LOCAL_DEV", False):
    # dict.fromkeys de-duplicates while preserving order; the default list above
    # already carries some of these.
    CORS_ALLOWED_ORIGINS = list(
        dict.fromkeys(CORS_ALLOWED_ORIGINS + LOCAL_DEV_CORS_ORIGINS)
    )

# --- Meilisearch -------------------------------------------------------------
# Read here rather than via os.getenv at import time inside content/views.py, so
# that a missing key degrades to a clean 503 from the search endpoint instead of
# configuring a half-built client at module import.
MEILISEARCH_URL = os.environ.get("MEILISEARCH_URL", "")
MEILISEARCH_MASTER_KEY = os.environ.get("MASTER_KEY", "")
MEILISEARCH_INDEX = os.environ.get("MEILISEARCH_INDEX", "content")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'accounts',
    'channel',
    'content',
    'corsheaders',
    'common',
]

CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", False)
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CBMTV API',
    'DESCRIPTION': 'API documentation for CBMTV',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    

]

ROOT_URLCONF = 'cbmtv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cbmtv.wsgi.application'
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Prefer an explicit DATABASE_URL if provided (e.g. by hosting platforms).
if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
# Fall back to explicit DB_* env vars for manually provided Postgres settings.
elif os.environ.get("DB_NAME"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
        }
    }
# Default to a local sqlite file when no DB settings are provided.
else:
    DATABASES = {
        "default": dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
# # Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Media storage is configured exclusively through backend environment variables.
# Credentials must never be exposed through frontend NEXT_PUBLIC_* variables.
MEDIA_STORAGE = {
    'PROVIDER': os.environ.get('MEDIA_STORAGE_PROVIDER', 's3').lower(),
    'CREDENTIALS_MODE': os.environ.get('AWS_CREDENTIALS_MODE', 'access_keys').lower(),
    'AWS_ACCESS_KEY_ID': os.environ.get('AWS_ACCESS_KEY_ID', ''),
    'AWS_SECRET_ACCESS_KEY': os.environ.get('AWS_SECRET_ACCESS_KEY', ''),
    'S3_BUCKET_NAME': os.environ.get('AWS_STORAGE_BUCKET_NAME', ''),
    'AWS_REGION': os.environ.get('AWS_S3_REGION_NAME', '').strip(),
    'CLOUDFRONT_BASE_URL': os.environ.get(
        'CLOUDFRONT_BASE_URL', os.environ.get('MEDIA_CDN_DOMAIN', '')
    ).strip().rstrip('/'),
    'CDN_DOMAIN': os.environ.get(
        'CLOUDFRONT_BASE_URL', os.environ.get('MEDIA_CDN_DOMAIN', '')
    ).strip().rstrip('/'),
    # Images are served straight from S3, not through CloudFront.
    # Optional override, e.g. an images-only CDN; defaults to the bucket URL.
    'IMAGE_BASE_URL': os.environ.get('MEDIA_IMAGE_BASE_URL', '').strip().rstrip('/'),
    # Floor for a presigned PUT's validity. The actual window is sized to the
    # declared upload size (see common.media_storage.resolve_presign_ttl), so a
    # large file gets a proportionally longer one, up to MAX_TTL.
    'PRESIGNED_URL_TTL': int(os.environ.get('MEDIA_PRESIGNED_URL_TTL', '3600')),
    'PRESIGNED_URL_MAX_TTL': int(os.environ.get('MEDIA_PRESIGNED_URL_MAX_TTL', '43200')),
    # Pessimistic floor rate used to turn bytes into seconds: the speed a
    # connection must beat, not a typical one. 100 KB/s ~= 0.8 Mbps.
    'MIN_UPLOAD_BYTES_PER_SEC': int(os.environ.get('MEDIA_MIN_UPLOAD_BYTES_PER_SEC', str(100 * 1024))),
    'PRESIGNED_URL_OVERHEAD': int(os.environ.get('MEDIA_PRESIGNED_URL_OVERHEAD', '300')),
    # S3 caps a single-part PUT at 5 GiB; anything larger needs multipart.
    'MAX_UPLOAD_BYTES': int(os.environ.get('MEDIA_MAX_UPLOAD_BYTES', str(5 * 1024**3))),
}
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
